# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a390b39169f07aa0db86cf74ad1449973e82c3d5ee32eae4f12a0e72afe53b4ec3827f32058e0a417fb57b834776ccacd7df1df0edb7ced1d4c0e001f7bd283c

test:
  secret_key_base: 8930b51082e72b5b0f1c2223a26595857c3c58c71090ebbcca62b3aa2e033103ce443e3b420f31c8b0e525c9106248956ea91ebc3281dadce3e18808269fb1bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
